### ISSUE TITLE
Wrong file during App scaffold

### ISSUE THREAD

**Issue by ajabep** [nextcloud/appstore#1053]
When trying to generate a scaffold for an app, the `lint-eslint.yml` file seems to be wrong. Indeed, it should use a variable that does not appear.

Indeed, when uploading the scaffold to GitHub, the action fails.

Example of the action of the generated files (without any edition) : https://github.com/ajabep/fileflow/actions/runs/5135261350/jobs/9240440791

## My analysis

These lines of the files seems to be wrong.

```yaml
      - name: Set up node $
        uses: actions/setup-node@v3
        with:
          node-version: $

      - name: Set up npm $
        run: npm i -g npm@"$"
```

They should be:

```yaml
      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"
```

## Details

* Browser and browser version: Last Google Chrome (done today)

## JavaScript Console Output

None, and not sure if that will help.

## Steps to reproduce

1. Fill the form @ https://apps.nextcloud.com/developer/apps/generate
2. Fill the "Nextcloud version" field with "25"
3. Download
4. Inspect the `.github/workflows/lint-eslint.yml` file.

Didn't try with other versions.

## Cause

I quickly took a look, and it seems to come from files as nextcloudappstore/scaffolding/app-templates/25/app/.github/workflows/lint-eslint.yml. It seems they are not well formatted.

## Solving

It seems that the template language print variables in `{{` and  `}}` tokens. Maybe write `{{ "{{" }}` and `{{ "}}" }}` instead should solve. Exclude this file from the generation should also solve it.
